### ISSUE TITLE
Droplet messes up justification

### ISSUE THREAD

**Issue by alerque** [EpicEricEE/typst-plugins#3]
Using the droplet package to add a drop cap seems to mess up justification on a pretty regular basis. It definitely doesn't break *every* time, but I ran into several metric combinations where the last line of the indented lines was not properly justified.

Here is an MWE:

```typst
#set page(
  paper: "a6",
)
#set par(
  justify: true,
)

#import "@preview/droplet:0.1.0": dropcap

#dropcap(
  justify: true,
  hanging-indent: 0pt,
)[
  This paragraph has a pretty plain initial or drop cap.
  It uses the default document font.
  You didn't really expect more detail with such a generic font choice, right?
]
```

![20231230_14h34m47s_grim](https://github.com/EpicEricEE/typst-plugins/assets/173595/7e4b90f3-4a9e-492a-ada1-5bf99908453f)

**Comment by EpicEricEE** [comment]
The problem seems to be that `didn't` is split up into the sequence `([didn], smartquote(double: false), [t])`. Breakpoints can be between spaces in text or between elements in a sequence, and in this case the breakpoint is exactly after `didn`, so it is put next to the dropcap. The `'t` would then be moved to the next line. It is currently not, because I think I'm missing a linebreak and Typst doesn't want to break before an apostrophe.

I should probably forbid breakpoints between elements in a sequence if there is no space. Until then, you can wrap the `didn't` in a box as a workaround. I can imagine that your other cases are due to a similar problem, let me know if that's not the case.

**Comment by alerque** [comment]
> Until then, you can wrap the `didn't` in a box as a workaround.

Unless I'm miss-understanding, this doesn't actually help. The results are the same.

Changing the input text from `didn't` to `didn’t` with the typographic glyph entered as U+2019 produces a better result, but ultimately any kind of wrapping or input modification is not a tenable solution for automated typesetting. If this is Typst bug let me know and I'll re-file over there.

**Comment by EpicEricEE** [comment]
>Unless I'm miss-understanding, this doesn't actually help. The results are the same.

Does it not give this result for you?

![image](https://github.com/EpicEricEE/typst-plugins/assets/7191192/e8be4f31-45d7-4883-bb53-4474f9c1ffee)

> any kind of wrapping or input modification is not a tenable solution for automated typesettin

Of course, it is just a suggestion until I have a fix. I wouldn't consider it a Typst bug, but rather a quirk of Typst that I didn't think about.

**Comment by alerque** [comment]
My bad, I tried `#text[]` and `#[]` not `#box[]`. I actually use `sile` not `typst` for most of my typesetting work and cross wired things in my head ;-)
