### ISSUE TITLE
Equate breaks cases function 

### ISSUE THREAD

**Issue by ItamarOlmert** [EpicEricEE/typst-plugins#9]
Note that
```
cases(
  a &= b\
  c &= d
)
```
Should produce the following:
![image](https://github.com/EpicEricEE/typst-plugins/assets/29255731/e63f2273-1fa8-4f64-8693-ed92afe4a569)
However, with the inclusion of the `equate` package, such as in the following example:
```
#import "@preview/equate:0.1.0": equate
#set math.equation(numbering: "(1.1)")
#show: equate.with(sub-numbering: true, number-mode: "label")
$
cases(
  a &= b\
  c &= d
)
$
```
The curly brace of the `cases` environment is absent, and the compiler warns `Layout did not converge within 5 attempts`:
![image](https://github.com/EpicEricEE/typst-plugins/assets/29255731/40d8d278-69da-485e-80b9-c78dc8c8066d)
Note that setting `number-mode: "line"` causes three `unexpected argument` errors. 
Another note, curiously enough, using the `equate.typ` file in the repository instead of importing from the `@preview` namespace results in the same behavior, but without compiler warnings.

**Comment by EpicEricEE** [comment]
That's weird, `vec` breaks in a similar way but `mat` seems to work.

As a workaround until I find a fix, you could put something invisible alongside the cases function, for example a zero width space (`zws`) or a single alignment point as in
```typ
$
  &cases(
    a &= b,
    c &= d
  )
$
```

As long as there is more than just the cases function, everything seems to work fine.

Also, the cases function is supposed to be used with commas instead of line breaks, but that doesn't really matter too much here :)
